### ISSUE TITLE
Import fails with virtual machines and activated qemu-agent

### ISSUE THREAD

**Issue by inno-mo** [nbuchwitz/icingaweb2-module-pve#13]
Hello Nicolai,

If I try to read the data with QEMU activated, I became this error Undefined array key "hardware-address" (Api.php:194)
On the Server there are Linux and Windows VMs.

If I turn the QEMU Agent in the PVE Plugin configuration off, I can read all data.

Please let me know if you need further information.

## Current Behavior
Undefined array key "hardware-address" (Api.php:194)

#0 /usr/share/icingaweb2/modules/pve/library/Pve/Api.php(194): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icingaweb2/modules/pve/library/Pve/ProvidedHook/Director/ImportSource.php(33): Icinga\Module\Pve\Api->getVMs()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(101): Icinga\Module\Pve\ProvidedHook\Director\ImportSource->fetchData()
#3 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#4 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#5 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(59): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#6 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(258): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator()
#7 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(186): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#11 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#12 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#14 {main}

## Your Environment

- **Icinga Web 2 PVE version** (System - About): 0.1.0
- **Icinga Web 2 version and modules**
  businessprocess 		2.4.0
  cube 		1.2.1 	
  director 		1.9.1 	
  doc 		2.11.1
  incubator 		0.18.0 
  monitoring 		2.11.1 	
  pve 		0.1.0 	
  setup 		2.11.1 	
  x509 		1.1.2
-**Version used** 
 icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.5-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 22.04.1 LTS (Jammy Jellyfish)
  Kernel: Linux
  Kernel version: 5.15.0-48-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 11.2.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

- **Operating System and version:** Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-48-generic x86_64)
-**Enabled features**
 Disabled features: compatlog debuglog elasticsearch gelf influxdb influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite icingadb ido-mysql mainlog notification

- **Config Validation**
[2022-09-30 06:15:30 +0000] information/cli: Icinga application loader (version: r2.13.5-1)
[2022-09-30 06:15:30 +0000] information/cli: Loading configuration file(s).
[2022-09-30 06:15:30 +0000] information/ConfigItem: Committing config item(s).
[2022-09-30 06:15:30 +0000] information/ApiListener: My API identity: icinga
[2022-09-30 06:15:30 +0000] warning/ApplyRule: Apply rule 'cluster' (in /etc/icinga2/conf.d/service.conf: 46:1-46:23) for type 'Service' does not match anywhere!
[2022-09-30 06:15:30 +0000] warning/ApplyRule: Apply rule 'storage ' (in /etc/icinga2/conf.d/service.conf: 121:1-121:73) for type 'Service' does not match anywhere!
[2022-09-30 06:15:30 +0000] warning/ApplyRule: Apply rule 'pve-vm ' (in /etc/icinga2/conf.d/service.conf: 130:1-130:72) for type 'Service' does not match anywhere!
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 7 Notifications.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 2 HostGroups.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 7 Hosts.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 IcingaDB.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 5 Zones.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 3 Endpoints.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 ApiUser.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 247 CheckCommands.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 1 User.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 34 Services.
[2022-09-30 06:15:30 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2022-09-30 06:15:30 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2022-09-30 06:15:30 +0000] information/cli: Finished validating the configuration file(s).

**Comment by nbuchwitz** [comment]
Should be fixed with #19
