### ISSUE TITLE
import fails with windows based virtual machines and activated qemu-agent

### ISSUE THREAD

**Issue by vita2** [nbuchwitz/icingaweb2-module-pve#2]
hello Nicolai,

guess i've found a bug. importing virtual machines with windows os will fail when the qemu agent is enabled. it seems the plugin cannot read the nic names. however it works with linux based virtual machines without any issues.

please let me know if you need further information.

## Current Behavior

```
Undefined index: name

#0 /usr/share/icingaweb2/modules/pve/library/Pve/Api.php(171): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/pve/library/Pve/ProvidedHook/Director/ImportSource.php(33): Icinga\Module\Pve\Api->getVMs(Boolean)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(109): Icinga\Module\Pve\ProvidedHook\Director\ImportSource->fetchData()
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(15): dipl\Web\Table\SimpleQueryBasedTable->getQuery()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(56): dipl\Web\Table\SimpleQueryBasedTable->getPaginationAdapter()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(237): dipl\Web\Table\QueryBasedTable->getPaginator(Object(dipl\Web\Url))
#7 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(145): dipl\Web\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

## Context

import source settings:

![import_source_settings](https://user-images.githubusercontent.com/25298055/50784744-de9dbe00-12ae-11e9-9e62-6818353176b4.png)

hardware of my windows 10 virtual machine:

![pve_windows_vm](https://user-images.githubusercontent.com/25298055/50784963-8fa45880-12af-11e9-94db-03fafd4c743d.png)

## Your Environment

* Icinga Web 2 PVE version (System - About): 0.1.0
* Icinga Web 2 version and modules (System - About):
   ```
   MODULE         VERSION   STATE     DESCRIPTION
   businessprocess 2.1.0     enabled   A Business Process viewer and modeler
   cube           1.0.1     enabled   Cube for Icinga Web 2
   director       master    enabled   Director - Config tool for Icinga 2
   doc            2.6.2     enabled   Documentation module
   fileshipper    1.1.0     enabled   Fileshipper for Icinga Director
   grafana        1.3.4     enabled   Grafana - A perfdata visualisation module
   ipl            v0.1.1    enabled   The Icinga PHP library
   map            1.1.0     enabled   Map - Visualize your hosts and service status
   mapDatatype    0.1.0     enabled   Location datatype for the director addon
   monitoring     2.6.2     enabled   Icinga monitoring module
   pve            0.1.0     enabled   Proxmox Virtual Environment (PVE) Import Source
   reactbundle    v0.4.1    enabled   ReactPHP-based 3rd party libraries
   theme-always-green master    enabled   Make the Monitoring green ;-)
   theme-dark     0.0.1     enabled   A dark theme for Icingaweb2
   theme-darkyellow 0.0.1     enabled   A dark theme for Icingaweb2
   x509           1.0.0     enabled   Scan and view X.509 certificate usage
   ```
* Version used (`icinga2 --version`):
   ```
   icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)
   
   Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
   License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.
   
   System information:
     Platform: Debian GNU/Linux
     Platform version: 9 (stretch)
     Kernel: Linux
     Kernel version: 4.9.0-8-amd64
     Architecture: x86_64
   
   Build information:
     Compiler: GNU 6.3.0
     Build host: 486e413fb159
   
   Application information:
   
   General paths:
     Config directory: /etc/icinga2
     Data directory: /var/lib/icinga2
     Log directory: /var/log/icinga2
     Cache directory: /var/cache/icinga2
     Spool directory: /var/spool/icinga2
     Run directory: /run/icinga2
   
   Old paths (deprecated):
     Installation root: /usr
     Sysconf directory: /etc
     Run directory (base): /run
     Local state directory: /var
   
   Internal paths:
     Package data directory: /usr/share/icinga2
     State path: /var/lib/icinga2/icinga2.state
     Modified attributes path: /var/lib/icinga2/modified-attributes.conf
     Objects path: /var/cache/icinga2/icinga2.debug
     Vars path: /var/cache/icinga2/icinga2.vars
     PID path: /run/icinga2/icinga2.pid
   ```
* Operating System and version: Debian Jessie 9.6 (4.9.0-8-amd64)
* Enabled features (`icinga2 feature list`): 
   ```
   Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata 
   statusdata syslog
   Enabled features: api checker command ido-mysql influxdb mainlog notification
   ```
* Config validation (`icinga2 daemon -C`): 
   ```
   [2019-01-03 16:02:19 +0100] information/cli: Icinga application loader (version: r2.10.2-1)
   [2019-01-03 16:02:19 +0100] information/cli: Loading configuration file(s).
   [2019-01-03 16:02:19 +0100] information/ConfigItem: Committing config item(s).
   [2019-01-03 16:02:19 +0100] information/ApiListener: My API identity: monitoring.home.lan
   [2019-01-03 16:02:20 +0100] warning/ApplyRule: Apply rule '' (in /var/lib/icinga2/api/packages/director/c9dfb6ef-64ac-433c
   -9554-bba143c71ec1/zones.d/director-global/service_apply.conf: 153:1-153:50) for type 'Service' does not match anywhere!
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 267 Services.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 InfluxdbWriter.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 19 Hosts.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 FileLogger.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 352 Dependencies.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 3 NotificationCommands.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 18 Notifications.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 15 HostGroups.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 ApiListener.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 7 Comments.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 12 Zones.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 10 Endpoints.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 3 ApiUsers.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 3 Users.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 205 CheckCommands.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 9 UserGroups.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 7 ServiceGroups.
   [2019-01-03 16:02:20 +0100] information/ConfigItem: Instantiated 12 TimePeriods.
   [2019-01-03 16:02:20 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
   [2019-01-03 16:02:20 +0100] information/cli: Finished validating the configuration file(s).
   ```

**Comment by nbuchwitz** [comment]
Sorry, I must somehow overlooked this issue. Could you share the API output of the VM?

```
pvesh get /nodes/<NODEDNAME>/qemu/<VMID>/agent/network-get-interfaces
```

**Comment by vita2** [comment]
sure! today i've updated the qemu agent version from 7.4.5 to 7.6.2 and the output changes as follows.

output with 7.4.5:
```
pvesh get /nodes/vidar/qemu/225/agent/network-get-interfaces --output-format json
{"result":{"error":{"class":"CommandDisabled","desc":"The command guest-network-get-interfaces has been disabled for this instance"}}}
```

output with 7.6.2:
```
pvesh get /nodes/vidar/qemu/225/agent/network-get-interfaces --output-format json
{"result":[{"hardware-address":"76:05:ee:b9:66:36","ip-addresses":[{"ip-address":"fe80::b51b:d3df:15df:19eb%3","ip-address-type":"ipv6","prefix":-1},{"ip-address":"192.168.25.45","ip-address-type":"ipv4","prefix":24}],"name":"Ethernet"},{"ip-addresses":[{"ip-address":"::1","ip-address-type":"ipv6","prefix":-1},{"ip-address":"127.0.0.1","ip-address-type":"ipv4","prefix":-1}],"name":"Loopback Pseudo-Interface 1"}]}
```

at the proxmox webui now i can see the network informations of my windows virtual machine.

![win_nics](https://user-images.githubusercontent.com/25298055/55746815-054ccb80-5a3b-11e9-9070-aa0003a5d1c4.png)

but the import still fails. there is a new exception:
```
Undefined index: hardware-address

#0 /usr/share/icingaweb2/modules/pve/library/Pve/Api.php(186): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/pve/library/Pve/ProvidedHook/Director/ImportSource.php(33): Icinga\Module\Pve\Api->getVMs(Boolean)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(109): Icinga\Module\Pve\ProvidedHook\Director\ImportSource->fetchData()
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(15): dipl\Web\Table\SimpleQueryBasedTable->getQuery()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(56): dipl\Web\Table\SimpleQueryBasedTable->getPaginationAdapter()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(237): dipl\Web\Table\QueryBasedTable->getPaginator(Object(dipl\Web\Url))
#7 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(145): dipl\Web\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

could be the blank characters in the loopback interface name the cause of this exception?

**Comment by nbuchwitz** [comment]
Thanks. These example above would lead to two tasks:

1. Check if there is any interface data from qemu-agent and ignore results if not
2. Ignore all interfaces with no ``hardware-addresss``

I'm not sure if I find time this week, but I'll keep it on my agenda.

**Comment by vita2** [comment]
unfortunately i don't know a way how to ignore this kind of network interfaces with qemu-agent :(

i've tried something else and modified the loopback nic detection a little bit:

```diff
diff --git a/library/Pve/Api.php b/library/Pve/Api.php
index cf92cc0..a963a98 100644
--- a/library/Pve/Api.php
+++ b/library/Pve/Api.php
@@ -168,7 +168,7 @@ class Api

                             foreach ($network as $row) {
                                 // skip loopback interface
-                                if (preg_match('/^lo.*/', $row['name'])) {
+                                if (preg_match('/^(lo.*|Loopback.*)/', $row['name'])) {
                                     continue;
                                 }
```

at least it solves the execption with the missing `hardware-address` value. what do you think?

![pve-import-preview](https://user-images.githubusercontent.com/25298055/55825887-1fec7680-5b07-11e9-962f-a294686e69a6.png)

**Comment by nbuchwitz** [comment]
I just pushed a fix for the loopback and missing interfaces. Could you please test with the GIT master?

**Comment by vita2** [comment]
thanks! i've just tested the latest commit. for me the issue is fixed 😃

**Comment by inno-mo** [comment]
I have the same Issue, the script from GIT master don't work for me. Any Ideas? 
Tested with icinga2 and Proxmox 7

**Comment by nbuchwitz** [comment]
@inno-mo please open a ticket with proper description & error message. Thanks
